config/routes.rb
Rails.application.routes.draw do
  get 'collaborators/index'

  resources :wikis do
    resources :collaborators, only: [:index, :create, :destroy]
  end
  resources :charges,  only: [:new, :create]
  get 'downgrade' => 'charges#destroy'

  devise_for :users
  resources :users, only: [:show]

  root 'wikis#index'

end

app/models/amount.rb
class Amount < ActiveRecord::Base
  def self.default
    15_00
  end
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :wikis
  has_many :collaborators

  enum role: [:standard, :premium, :admin]
  after_initialize :default_user_role, :if => :new_record?

  def default_user_role
    self.role ||= :standard
  end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators

  scope :visible_to, -> (user) { user ? all : where(private: false) }

  def collaborator_for(user)
    collaborators.where(user_id: user.id).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  protect_from_forgery with: :exception


  private

  def user_not_authorized
    flash[:alert] = "Access denied"
    redirect_to (request.referrer || root_path)
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Blocipedia Premium Membership - #{current_user.email}",
      amount: Amount.default
    }
  end

  def create
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: Amount.default,
      description: "Premium Membership - #{current_user.email}",
      currency: 'usd'
    )

    current_user.premium!

    flash[:notice] = "Thanks! Enjoy your premium membership #{current_user.email}"
    redirect_to root_path

  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to new_charge_path
  end

  def destroy
    current_user.standard!

    current_user.wikis.each do |wikis|
      wikis.update_attributes(private: false)
    end

    flash[:notice] = "Membership has been downgraded to Standard"
    redirect_to wikis_path
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController

  before_action :set_wiki

  def index
    @users = User.all
  end

  def create
    @collaborator = @wiki.collaborators.new(user_id: params[:user_id])
    if @collaborator.save
      flash[:notice] = "Your collaborator was added"
    else
      flash[:alert] = "Whoops! There was an error, please try again."
    end
    redirect_to wiki_collaborators_path(@wiki)
  end

  def destroy
    @collaborator = Collaborator.find(params[:id])
    if @collaborator.destroy
      flash[:notice] = "Your collaborator was removed"
    else
      flash[:alert] = "Whoops! There was an error, please try again."
    end
    redirect_to wiki_collaborators_path(@wiki)
  end

  private
  def set_wiki
    @wiki = Wiki.find(params[:wiki_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    current_user
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :set_wiki, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :index, :show]

  # GET /wikis
  def index
    @wikis = policy_scope(Wiki)
  end

  # GET /wikis/1
  def show
    authorize @wiki
   end

  # GET /wikis/new
  def new
    @wiki = Wiki.new
  end

  # GET /wikis/1/edit
  def edit
    authorize @wiki
  end

  # POST /wikis
  def create
    @wiki = current_user.wikis.new(wiki_params)

    respond_to do |format|
      if @wiki.save
        format.html { redirect_to @wiki, notice: 'Wiki was successfully created.' }
        format.json { render :show, status: :created, location: @wiki }
      else
        format.html { render :new }
        format.json { render json: @wiki.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wikis/1
  def update
    authorize @wiki
    respond_to do |format|
      if @wiki.update(wiki_params)
        format.html { redirect_to @wiki, notice: 'Wiki was successfully updated.' }
        format.json { render :show, status: :ok, location: @wiki }
      else
        format.html { render :edit }
        format.json { render json: @wiki.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wikis/1
  def destroy
    authorize @wiki
    @wiki.destroy
    respond_to do |format|
      format.html { redirect_to wikis_url, notice: 'Wiki was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_wiki
      @wiki = Wiki.find(params[:id])
    end

    def wiki_params
      params.require(:wiki).permit(:title, :body, :private, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<div class="container">


<% if current_user && current_user.standard? %>
  <p>Enjoy even more from Blocipedia, upgrade your account to Premium</p>
<%= form_tag charges_path do %>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>
<% end %>

<% if current_user && current_user.premium? %>
<h3>Are you sure you wish to Downgrade you account? You will no longer be able to use private wikis.</h3>
  <%= link_to "Downgrade Account", downgrade_path, class: "btn btn-danger" %>
<% end %>
</div>

app/views/collaborators/_form.html.erb
<div class="form-group">
  <%= f.label :collaborators %>
  <%= f.text_field :collaborators, class: 'form-control', placeholder: 'Add Collaborator' %>
</div>

app/views/collaborators/index.html.erb
<h1>Collaborators for <%= @wiki.title %></h1>

<table class="table table-striped">
  <thead>
    <th>
      Email
    </th>
    <th></th>
  </thead>
  <% @users.each do |user| %>
    <tr>
      <td>
        <%= user.email %>
      </td>
      <td>
        <% if @wiki.users.include?(user) %>
        <% collaborator = @wiki.collaborator_for(user) %>
          <%= link_to "Remove as Collaborator", wiki_collaborator_path(@wiki, collaborator), method: :delete, class: "btn btn-danger" %>
        <% else %>
          <%= link_to "Add as Collaborator", wiki_collaborators_path(@wiki, user_id: user.id), method: :post, class: "btn btn-success" %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

<%= link_to "Back to Edit", edit_wiki_path(@wiki), class: "btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
    <% if user_signed_in? %>
    Welcome, <strong><%= current_user.email %></strong> |
    <%= link_to 'Edit profile', edit_user_registration_path, class: 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
  <% else %>
    <%= link_to "Sign Up", new_user_registration_path, class: 'navbar-link'  %> -
    <%= link_to "Sign In", new_user_session_path, class: 'navbar-link'  %>
  <% end %>
  <div class="pull-right">
    <% if current_user && current_user.standard? %>
      <%= link_to "Upgrade to Premium", new_charge_path %>
    <% end %>
    <% if current_user && current_user.premium? %>
      <%= link_to "Downgrade Account", new_charge_path %>
    <% end %>
  </div>
</div>




<div class="container">
  <div class="flash">
    <% if flash[:notice] %>
       <div class="alert alert-success">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:notice] %>
       </div>
     <% elsif flash[:error] %>
       <div class="alert alert-danger">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:error] %>
       </div>
     <% elsif flash[:alert] %>
       <div class="alert alert-warning">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:alert] %>
       </div>
     <% end %>
   </div>
   
  <%= yield %>
</div>

</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Membership</title>
</head>

<body>
  <% if user_signed_in? %>

  <%= link_to "Home", wikis_path, class: 'navbar-link' %> -
  <%= link_to 'Edit profile', edit_user_registration_path, class: 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
<% else %>
  <%= link_to "Sign Up", new_user_registration_path, class: 'navbar-link'  %> -
  <%= link_to "Sign In", new_user_session_path, class: 'navbar-link'  %>
<% end %>
  <%= yield %>
</body>
</html>

app/views/users/show.html.erb
<h3>User</h3>
<%= current_user.email %>

app/views/wikis/_form.html.erb
<%= form_for(@wiki) do |f| %>
  <% if @wiki.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wiki.errors.count, "error") %> prohibited this wiki from being saved:</h2>

      <ul>
      <% @wiki.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
<% if current_user.admin? || current_user.premium? %>
  <div class="form-group">
    <%= f.label :private, class: 'checkbox' do %>
    <%= f.check_box :private %> Private Wiki
    <% end %>
  </div>
<% end %>


  <div class="actions">
    <%= f.submit %>
  </div>
    <% end %>

app/views/wikis/edit.html.erb
<h1>Editing Wiki</h1>

<%= render 'form' %>
  <div class="manage_collaborators">
    <%= link_to "Manage Collaborators", wiki_collaborators_path(@wiki), class: "btn btn-success" %>
  </div>

<%= link_to 'Show', @wiki %> |
<%= link_to 'Home', wikis_path %>

app/views/wikis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wikis</h1>
    <% if user_signed_in? %>
    <%= link_to 'New Wiki', new_wiki_path, class: 'btn btn-primary' %>
    <% end %>
<br></br>

<% @wikis.each do |wiki| %>
  <div class="col-md-8">
    <h2><%= wiki.title %></h2>
    <small>By <%= wiki.user.email %> <%= "Private" if wiki.private? %></small>
    <p>
      <%= wiki.body %>
    </p>
  </div>
  <div class="col-md-4">
    <%= link_to 'Read', wiki, class: 'btn btn-default' %>
    <%= link_to 'Edit', edit_wiki_path(wiki), class: 'btn btn-default' %>
    <%= link_to 'Delete', wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %>
  </div> 
<% end %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<%= render 'form' %>

<%= link_to 'Back', wikis_path %>

app/views/wikis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @wiki.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= markdown(@wiki.body) %>
</p>

<p>
  <strong>Private:</strong>
  <%= @wiki.private %>
</p>

<p>
  <strong>User:</strong>
  <%= @wiki.user.email if @wiki.user %>
</p>

<%= link_to 'Edit', edit_wiki_path(@wiki) %> |
<%= link_to 'Home', wikis_path %>